/**
 * Electrical pack (Team G, 2026-09-24). See
 * handoffs/INDUSTRY_EXPANSION_2026-09-21.md ("1. Electrical") for the
 * ICP/document-set/warranty research this is built from.
 */

const documentTypes = [
  { id: 'work-order', label: 'Work order', definition: 'A dispatched job: address, date, electrician, and what to do — not yet completed.', requires: ['service_address', 'service_date', 'technician'], visitType: true, financial: false },
  { id: 'invoice', label: 'Invoice', definition: 'A bill for work or equipment: a customer, a charge, a total cost.', requires: ['service_address', 'cost'], visitType: true, financial: true },
  { id: 'warranty-registration', label: 'Warranty registration', definition: 'Registers a panel, generator or EV charger with the manufacturer for warranty coverage.', requires: ['serial_number', 'model', 'warranty_expires|warranty_term'], visitType: false, financial: false },
  { id: 'startup-sheet', label: 'Startup sheet', definition: 'Records commissioning readings for newly installed equipment (a generator or EV charger).', requires: ['serial_number', 'service_date'], visitType: true, financial: false },
  { id: 'permit', label: 'Permit', definition: 'A government or utility permit for electrical work, carrying a permit number.', requires: ['service_address', 'permit_number'], visitType: false, financial: false },
  { id: 'nameplate-photo', label: 'Nameplate photo', definition: 'A photo of a panel or generator data plate: just serial and model, no service context.', requires: ['serial_number', 'model'], visitType: false, financial: false },
  { id: 'maintenance-agreement', label: 'Maintenance agreement', definition: 'A recurring service contract, commonly a generator service plan.', requires: ['service_address', 'customer_name', 'warranty_term|agreement_term'], visitType: false, financial: true },
  { id: 'service-ticket', label: 'Service ticket', definition: 'A completed service visit: what was found and what was done.', requires: ['service_address', 'service_date', 'work_performed'], visitType: true, financial: false },
  { id: 'dispatch-note', label: 'Dispatch note', definition: 'A short note dispatching an electrician, with little other detail.', requires: ['customer_name|service_address', 'service_date'], visitType: true, financial: false },
  { id: 'proposal-quote', label: 'Proposal / quote', definition: 'A proposed price for work not yet performed.', requires: ['customer_name|service_address', 'cost'], visitType: false, financial: true },
  { id: 'inspection-report', label: 'Inspection report', definition: 'Findings from inspecting electrical work — rough-in, final, AFCI/GFCI test results.', requires: ['service_address', 'service_date'], visitType: true, financial: false },
  { id: 'purchase-order', label: 'Purchase order', definition: 'An order placed with a vendor for parts or equipment.', requires: ['vendor|customer_name', 'cost'], visitType: false, financial: true },
  { id: 'equipment-record', label: 'Equipment record', definition: 'Identifies a panel, generator or charger with no service or billing context.', requires: ['serial_number|model'], visitType: false, financial: false },
  { id: 'correspondence', label: 'Correspondence', definition: 'A letter or email about a customer or job, not a paperwork form.', requires: ['customer_name'], visitType: false, financial: false },
  { id: 'internal', label: 'Shop record', definition: 'Shop-only record with no customer on it at all.', requires: [], visitType: false, financial: false },
  { id: 'other', label: 'Other', definition: 'Does not clearly fit any type above.', requires: [], visitType: true, financial: false },
  // Electrical-specific, per the expansion brief's "▲" addition:
  { id: 'panel-schedule', label: 'Panel schedule', definition: 'Maps a panel\'s breakers to circuits/loads — the whole panel\'s circuit map, not one equipment record.', requires: ['service_address', 'amperage'], visitType: false, financial: false },
];

const fields = [
  { key: 'equipment_id', label: 'Equipment ID', perUnit: true, description: 'Internal panel/generator ID the company uses (e.g. "Panel-A"). NOT the serial number.' },
  { key: 'serial_number', label: 'Serial number', perUnit: true, description: 'Manufacturer serial number, exactly as printed.' },
  { key: 'model', label: 'Model', perUnit: true, description: 'Model name or number, exactly as printed.' },
  { key: 'manufacturer', label: 'Manufacturer', perUnit: true, description: 'Manufacturer (Square D, Siemens, Eaton, Generac, ChargePoint, Tesla, Leviton, ...).' },
  { key: 'equipment_type', label: 'Equipment type', perUnit: true, description: 'What the unit is: panel, sub-panel, generator, EV charger, disconnect, meter.' },
  { key: 'amperage', label: 'Amperage', perUnit: true, description: 'Main breaker/service rating as printed, e.g. "200 amp", "100 amp".' },
  { key: 'voltage', label: 'Voltage', perUnit: true, description: 'Nominal voltage as printed, e.g. "240V", "120/240V".' },
  { key: 'phase', label: 'Phase', perUnit: true, description: 'Single-phase or three-phase, as printed.' },
  { key: 'afci_gfci', label: 'AFCI/GFCI protection', perUnit: false, description: 'Whether AFCI/GFCI protection is documented on this job — yes/no or which circuits.' },
  { key: 'service_address', label: 'Service address', perUnit: false, description: 'Street address where the work was performed — not the contractor\'s own letterhead address.' },
  { key: 'shop_address', label: 'Shop address', perUnit: false, description: 'The electrical contractor\'s own business/letterhead address.' },
  { key: 'shop_phone', label: 'Shop phone', perUnit: false, description: 'The electrical contractor\'s own business/letterhead phone number.' },
  { key: 'shop_email', label: 'Shop email', perUnit: false, description: 'The electrical contractor\'s own business/letterhead email address.' },
  { key: 'customer_name', label: 'Customer', perUnit: false, description: 'Customer or account name.' },
  { key: 'customer_phone', label: 'Customer phone', perUnit: false, description: 'Customer phone number, exactly as printed.' },
  { key: 'customer_email', label: 'Customer email', perUnit: false, description: 'Customer email address, exactly as printed.' },
  { key: 'installation_date', label: 'Installation date', perUnit: true, description: 'Date the equipment was installed.' },
  { key: 'warranty_expires', label: 'Warranty expires', perUnit: false, description: 'Date the warranty expires.' },
  { key: 'warranty_term', label: 'Term', perUnit: false, description: 'The manufacturer warranty length for the equipment itself, e.g. generator "5 year limited".' },
  { key: 'agreement_term', label: 'Agreement term', perUnit: false, description: 'The service/maintenance agreement period between the customer and the electrical company.' },
  { key: 'warranty_registered_date', label: 'Warranty registered', perUnit: false, description: 'Date the warranty was registered with the manufacturer.' },
  { key: 'service_date', label: 'Service date', perUnit: false, description: 'Date service was performed.' },
  { key: 'service_type', label: 'Service type', perUnit: false, description: 'Preventive Maintenance, Repair, Emergency, Installation, Inspection, Panel Upgrade, EV Charger Install.' },
  { key: 'technician', label: 'Technician', perUnit: false, description: 'Name of the electrician who performed the work.' },
  { key: 'work_performed', label: 'Work performed', perUnit: false, description: 'One work item performed. Return one field per item, not a joined list.' },
  { key: 'part_number', label: 'Part number', perUnit: false, description: 'A part number referenced on the document.' },
  { key: 'cost', label: 'Cost', perUnit: false, description: 'Total amount charged, in dollars.' },
  { key: 'labor_hours', label: 'Labor hours', perUnit: false, description: 'Labor hours billed.' },
  { key: 'invoice_number', label: 'Invoice number', perUnit: false, description: 'Invoice, ticket, or work-order number.' },
  { key: 'status', label: 'Status', perUnit: false, description: 'Completed, Pending, In Progress, Passed, Failed.' },
  { key: 'notes', label: 'Notes', perUnit: false, description: 'A short observation that does not fit another field.' },
  { key: 'permit_number', label: 'Permit number', perUnit: false, description: 'A government or utility permit number referenced on the document.' },
];

const brands = ['Square D', 'Siemens', 'Eaton', 'Generac', 'ChargePoint', 'Tesla', 'Leviton', 'Cutler-Hammer', 'GE', 'Kohler'];

const synonyms = {
  panel: ['panel', 'panels', 'breaker panel', 'breaker box', 'load center', 'electrical panel', 'main panel'],
  'panel upgrade': ['panel upgrade', 'service upgrade', 'panel upgrades', 'service upgrades'],
  generator: ['generator', 'generators', 'genset', 'standby generator'],
  'ev charger': ['ev charger', 'ev chargers', 'electric vehicle charger', 'charging station', 'car charger'],
  breaker: ['breaker', 'breakers', 'circuit breaker'],
  gfci: ['gfci', 'ground fault', 'ground fault circuit interrupter'],
  afci: ['afci', 'arc fault', 'arc fault circuit interrupter'],
  'load calc': ['load calc', 'load calculation', 'load calculations'],
  disconnect: ['disconnect', 'disconnects', 'disconnect switch'],
  'fuse box': ['fuse box', 'fuse boxes', 'fused panel'],
  outage: ['outage', 'outages', 'power outage', 'no power'],
  spark: ['spark', 'sparking', 'sparks', 'arcing'],
};

const abbreviations = { amp: 'amperage', amps: 'amperage', v: 'voltage', gfci: 'gfci', afci: 'afci', ev: 'electric vehicle', po: 'purchase order' };
const typos = { panle: 'panel', braker: 'breaker', genrator: 'generator', ampereage: 'amperage' };

const personas = [
  {
    id: 'dispatcher',
    label: 'Dispatcher',
    sampleQuestions: [
      'How many customers have a 200-amp panel installed?',
      'Which customers still have a 100-amp panel?',
      'How many panel upgrades did we do this year?',
      'Is the panel at 412 Elm St still under warranty?',
      'Who installed the generator at 88 Cactus Rd and when?',
      'How many customers have a Generac generator?',
      'List customers with EV chargers installed.',
      'How many EV charger installs did we do in Chandler?',
      'Which jobs are missing a final inspection?',
      'How many open permits do we have?',
      'What is the panel\'s main breaker rating at 200 Main St?',
      'How many customers in Mesa have had a service upgrade?',
      'Which customers have generators under a maintenance agreement?',
      'How many callbacks did we have on panel jobs last month?',
      'List all customers with Square D panels.',
      'How many customers are still on a fuse box, not a breaker panel?',
      'What permit number was pulled for the job at 300 Oak Ave?',
      'How many inspections failed on the first attempt this year?',
      'Which technician installed the most panels this quarter?',
      'How many customers have AFCI/GFCI protection documented?',
      'How many documents mention a tripped breaker?',
      'How many jobs mention arcing or sparking?',
      'Which customers had a load calculation performed?',
      'How many disconnect switches have we installed?',
      'How many generators are under warranty right now?',
      'What is the average cost of a panel upgrade?',
    ],
  },
  {
    id: 'owner',
    label: 'Shop owner',
    sampleQuestions: [
      'How much have we invoiced for panel upgrades this year?',
      'How many warranty registrations are missing a serial number?',
      'How many permits are still open across all jobs?',
      'How many maintenance agreements do we have for generators?',
      'How many EV charger installs have we completed in total?',
      'How many distinct panel manufacturers are on file?',
    ],
  },
];

const examTemplates = [
  { id: 'elec-count-invoices', category: 'financial', question: 'How many invoices do we have on file?', oracle: 'count_documents_by_type:invoice', compare: 'number', citationRequired: false },
  { id: 'elec-sum-invoice-total', category: 'financial', question: 'What is the total of every invoice on file?', oracle: 'sum_financials_total:invoice', compare: 'number', citationRequired: true },
  { id: 'elec-unpaid-invoices', category: 'financial', question: 'How many invoices are unpaid?', oracle: 'count_financials_by_status:unpaid', compare: 'number', citationRequired: false },
  { id: 'elec-count-customers-with-invoice', category: 'financial', question: 'How many customers have at least one invoice?', oracle: 'count_customers_with_doctype:invoice', compare: 'number', citationRequired: false },
  { id: 'elec-avg-cost', category: 'financial', question: 'What is the average cost across every invoice on file?', oracle: 'avg_numeric_field:cost', compare: 'number', citationRequired: false },
  { id: 'elec-sum-proposal-total', category: 'financial', question: 'What is the total of every open proposal/quote?', oracle: 'sum_financials_total:estimate', compare: 'number', citationRequired: true },
  { id: 'elec-count-warranty-regs', category: 'warranty', question: 'How many warranty registrations are on file?', oracle: 'count_documents_by_type:warranty-registration', compare: 'number', citationRequired: false },
  { id: 'elec-count-warranty-expires', category: 'warranty', question: 'How many documents record a warranty expiration date?', oracle: 'count_documents_with_field:warranty_expires', compare: 'number', citationRequired: false },
  { id: 'elec-count-warranty-term', category: 'warranty', question: 'How many documents record a warranty term?', oracle: 'count_documents_with_field:warranty_term', compare: 'number', citationRequired: false },
  { id: 'elec-missing-warranty-serial', category: 'warranty', question: 'How many warranty registrations are missing a serial number?', oracle: 'count_documents_missing_field:warranty-registration:serial_number', compare: 'honest-zero', citationRequired: false },
  { id: 'elec-warranty-expiring-90', category: 'warranty', question: 'How many warranties expire in the next 90 days?', oracle: 'count_field_date_within_days:warranty_expires:90', compare: 'number', citationRequired: true },
  { id: 'elec-warranty-expired', category: 'warranty', question: 'How many warranties have already expired?', oracle: 'count_field_date_before_today:warranty_expires', compare: 'number', citationRequired: true },
  { id: 'elec-count-panel-schedules', category: 'equipment', question: 'How many panel schedules are on file?', oracle: 'count_documents_by_type:panel-schedule', compare: 'number', citationRequired: false },
  { id: 'elec-distinct-amperage', category: 'equipment', question: 'How many distinct amperage ratings are on file?', oracle: 'count_distinct_field_values:amperage', compare: 'number', citationRequired: false },
  { id: 'elec-count-amperage-field', category: 'equipment', question: 'How many documents record an amperage rating?', oracle: 'count_documents_with_field:amperage', compare: 'number', citationRequired: false },
  { id: 'elec-200amp', category: 'equipment', question: 'How many documents record a 200 amp service?', oracle: 'count_field_value_matches:amperage:200', compare: 'number', citationRequired: true },
  { id: 'elec-100amp', category: 'equipment', question: 'How many documents record a 100 amp service?', oracle: 'count_field_value_matches:amperage:100', compare: 'number', citationRequired: true },
  { id: 'elec-distinct-manufacturers', category: 'equipment', question: 'How many distinct equipment manufacturers are on file?', oracle: 'count_distinct_field_values:manufacturer', compare: 'number', citationRequired: false },
  { id: 'elec-distinct-equipment-type', category: 'equipment', question: 'How many distinct equipment types are on file?', oracle: 'count_distinct_field_values:equipment_type', compare: 'number', citationRequired: false },
  { id: 'elec-count-afci-gfci', category: 'compliance', question: 'How many documents record AFCI/GFCI protection?', oracle: 'count_documents_with_field:afci_gfci', compare: 'number', citationRequired: false },
  { id: 'elec-count-inspections', category: 'compliance', question: 'How many inspection reports are on file?', oracle: 'count_documents_by_type:inspection-report', compare: 'number', citationRequired: false },
  { id: 'elec-count-permits', category: 'compliance', question: 'How many permits are on file?', oracle: 'count_documents_by_type:permit', compare: 'number', citationRequired: false },
  { id: 'elec-count-permits-with-number', category: 'compliance', question: 'How many documents record a permit number?', oracle: 'count_documents_with_field:permit_number', compare: 'number', citationRequired: false },
  { id: 'elec-inspections-missing-date', category: 'compliance', question: 'How many inspection reports are missing a service date?', oracle: 'count_documents_missing_field:inspection-report:service_date', compare: 'honest-zero', citationRequired: false },
  { id: 'elec-count-customers', category: 'entities', question: 'How many customers are on file?', oracle: 'count_entities_by_type:customer', compare: 'number', citationRequired: false },
  { id: 'elec-count-equipment', category: 'entities', question: 'How many pieces of equipment are on file?', oracle: 'count_entities_by_type:equipment', compare: 'number', citationRequired: false },
  { id: 'elec-count-technicians', category: 'entities', question: 'How many technicians are on file?', oracle: 'count_entities_by_type:technician', compare: 'number', citationRequired: false },
  { id: 'elec-count-maintenance-agreements', category: 'entities', question: 'How many maintenance agreements do we have?', oracle: 'count_documents_by_type:maintenance-agreement', compare: 'number', citationRequired: false },
  { id: 'elec-mentions-generator', category: 'content', question: 'How many documents mention a generator?', oracle: 'count_documents_mentioning:generator', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-ev-charger', category: 'content', question: 'How many documents mention an EV charger?', oracle: 'count_documents_mentioning:ev\\s+charger|electric\\s+vehicle\\s+charger', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-panel-upgrade', category: 'content', question: 'How many documents mention a panel upgrade?', oracle: 'count_documents_mentioning:panel\\s+upgrade', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-tripped-breaker', category: 'content', question: 'How many documents mention a tripped breaker?', oracle: 'count_documents_mentioning:tripped\\s+breaker', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-arcing', category: 'content', question: 'How many documents mention arcing or sparking?', oracle: 'count_documents_mentioning:arcing|sparking', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-load-calc', category: 'content', question: 'How many documents mention a load calculation?', oracle: 'count_documents_mentioning:load\\s+calc', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-fuse-box', category: 'content', question: 'How many documents mention a fuse box?', oracle: 'count_documents_mentioning:fuse\\s+box', compare: 'number', citationRequired: true },
  { id: 'elec-mentions-outage', category: 'content', question: 'How many documents mention a power outage?', oracle: 'count_documents_mentioning:outage', compare: 'number', citationRequired: true },
  { id: 'elec-count-work-orders', category: 'operations', question: 'How many work orders are on file?', oracle: 'count_documents_by_type:work-order', compare: 'number', citationRequired: false },
  { id: 'elec-count-service-tickets', category: 'operations', question: 'How many service tickets are on file?', oracle: 'count_documents_by_type:service-ticket', compare: 'number', citationRequired: false },
  { id: 'elec-count-technician-field', category: 'operations', question: 'How many documents record a technician name?', oracle: 'count_documents_with_field:technician', compare: 'number', citationRequired: false },
  { id: 'elec-count-documents-total', category: 'operations', question: 'How many documents do we have on file in total?', oracle: 'count_documents_total', compare: 'number', citationRequired: false },
  { id: 'elec-avg-labor-hours', category: 'operations', question: 'What is the average labor hours billed across every job?', oracle: 'avg_numeric_field:labor_hours', compare: 'number', citationRequired: false },
];

const electricalPack = {
  id: 'electrical',
  label: 'Electrical',
  businessNoun: 'electrical contractor',
  unitNoun: 'panel',
  documentTypes,
  fields,
  brands,
  synonyms,
  abbreviations,
  typos,
  maintenance: {
    defaultCadenceMonths: 12,
    cadencePhrases: [
      { re: '\\bgenerator\\b[^?]*\\b(?:service|maintenance)\\b[^?]*\\bannual', months: 12 },
      { re: '\\bpanel\\b[^?]*\\binspection\\b[^?]*\\bevery\\s+three\\s+years\\b', months: 36 },
    ],
    seasons: { spring: [3, 5], summer: [6, 8], fall: [9, 11], winter: [12, 2] },
  },
  warranty: {
    brandRules: {
      generac: { label: 'Generac', rule: { registrationWindowDays: 90, unregisteredPartsYears: 2, registeredPartsYears: 5 }, confidence: 'medium', notes: 'Standby generator; term often capped by run-hours, not just calendar years.' },
      'square-d': { label: 'Square D', aliases: ['square d'], rule: { registrationWindowDays: 0, unregisteredPartsYears: 1, registeredPartsYears: 1 }, confidence: 'medium', notes: 'Breakers/panel enclosures: breakers ~1yr, some enclosures up to 10yr; contractor-set labor warranty typically 1-2yr, not code-mandated.' },
      chargepoint: { label: 'ChargePoint', rule: { registrationWindowDays: 30, unregisteredPartsYears: 2, registeredPartsYears: 3 }, confidence: 'medium', notes: 'EV charger hardware warranty commonly 2-3yr.' },
      tesla: { label: 'Tesla', rule: { registrationWindowDays: 30, unregisteredPartsYears: 4, registeredPartsYears: 4 }, confidence: 'medium', notes: 'Wall Connector hardware warranty commonly 4yr.' },
    },
  },
  personas,
  examTemplates,
};

export default electricalPack;
