/**
 * Donovan Scorecard - loads the golden exam (test-docs/scorecard/exam.json, generated by
 * scripts/gen-scorecard.mjs from the question bank). Tolerant of the file not being shipped: returns an empty
 * exam with a single warning, never throws. Cached after the first successful load.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
let cached; // undefined = not tried; object = loaded (possibly empty)
let warned = false;

// "count-with-unknown" (TEAM F, 2026-09-24): a status-derived count (invoices unpaid/paid/overdue/partial)
// where most rows print no status at all - see compare.js's compareCountWithUnknown.
const VALID_CMP = new Set(["number", "set", "value", "yesno", "honest-zero", "rubric", "count-with-unknown"]);

/** Pure: keep only well-formed questions. */
export function validQuestions(list) {
  return (Array.isArray(list) ? list : []).filter((q) => q && typeof q.id === "string" && typeof q.text === "string" && q.text.length <= 300
    && typeof q.category === "string" && VALID_CMP.has(q.cmp) && q.oracle && typeof q.oracle.sql === "string" && (q.cmp !== "rubric" || typeof q.rubric === "string"));
}

export function loadExam() {
  if (cached !== undefined) return cached;
  try {
    const raw = readFileSync(join(__dirname, "..", "..", "..", "test-docs", "scorecard", "exam.json"), "utf8");
    const parsed = JSON.parse(raw);
    cached = { version: String(parsed.version ?? "unknown"), questions: validQuestions(parsed.questions) };
  } catch (err) {
    if (!warned) { warned = true; console.warn("scorecard: exam.json not found (run `node scripts/gen-scorecard.mjs`):", err?.message); }
    cached = { version: "missing", questions: [] };
  }
  return cached;
}

export function resetExamCacheForTests() { cached = undefined; }
