// Jargon round (J2) page-text fixtures for verify-field-synonyms.ts. Each is realistic paperwork from a different
// industry using labels from the jargon research. `want` = exactly the values a reader may emit (fewer is fine, different
// is a failure); `must` = the recall floor for the stored-text read; `never` = keys that must not be emitted at all.
// The last three are PROSE: the same label words inside sentences. Nothing may be read from them.
type Fx = { name: string; own: string[]; type: string; text: string; want: Record<string, string>; must: string[]; never?: string[] };
const L = (...lines: string[]) => lines.join('\n');
const DP = ['Desert Peak Services LLC'];

export const FX2: Fx[] = [
  { name: 'COI whose policy dates are only a page reference (QA)', own: DP, type: 'insurance-certificate',
    text: L('CERTIFICATE OF LIABILITY INSURANCE', 'Named Insured: Cactus Roofing Inc', 'Policy dates: see page 2', 'Policy period: see page 2', 'Certificate Holder: Desert Peak Services LLC'),
    want: { vendor: 'Cactus Roofing Inc' }, must: [], never: ['agreement_term', 'customer_name', 'cost'] },
  { name: 'pay app (construction progress invoice)', own: DP, type: 'invoice',
    text: L('PAY APPLICATION', 'Pay App #: 4', 'Application Date: 10/02/2026', 'Bill To: Mesa Unified Facilities', 'Project: Gym roof replacement', 'Please Remit: $42,500.00'),
    want: { customer_name: 'Mesa Unified Facilities', service_date: '2026-10-02', cost: '42500.00', invoice_number: '4' }, must: ['customer_name', 'service_date', 'cost'] },
  { name: 'credit memo (negative invoice)', own: DP, type: 'invoice',
    text: L('CREDIT MEMO', 'Credit Memo #: CM-2207', 'Credit Date: 05/04/2026', 'Customer: Lena Ortiz', 'Reason: returned filter set', 'Credit Total: $85.00'),
    want: { customer_name: 'Lena Ortiz', service_date: '2026-05-04', cost: '85.00', invoice_number: 'CM-2207' }, must: ['customer_name', 'service_date', 'cost', 'invoice_number'] },
  { name: 'COI, ACORD 25 style (named insured, policy dates)', own: DP, type: 'insurance-certificate',
    text: L('ACORD 25 CERTIFICATE OF LIABILITY INSURANCE', 'Date Issued: 03/01/2026', 'Named Insured: Cactus Roofing Inc', 'Policy Number: GL-0099871', 'Policy Effective Date: 03/01/2026', 'Policy Expiration Date: 03/01/2027', 'Certificate Holder: Desert Peak Services LLC'),
    want: { vendor: 'Cactus Roofing Inc', service_date: '2026-03-01', agreement_term: '03/01/2026 - 03/01/2027' }, must: ['vendor'], never: ['customer_name', 'cost'] },
  { name: 'COI, proof of insurance with an insured and a policy period', own: DP, type: 'insurance-certificate',
    text: L('PROOF OF INSURANCE', 'Insured: Blue Mesa Analytics Inc', 'Policy No: WC-55120', 'Policy Period: 07/01/2026 - 07/01/2027', 'Certificate Holder: Desert Peak Services LLC'),
    want: { vendor: 'Blue Mesa Analytics Inc', agreement_term: '07/01/2026 - 07/01/2027' }, must: ['vendor'], never: ['customer_name', 'cost'] },
  { name: 'lien-waiver style text (claimant releases payment)', own: DP, type: 'agreement',
    text: L('CONDITIONAL WAIVER AND RELEASE ON PROGRESS PAYMENT', 'Customer: Mesa Unified Facilities', 'Date Signed: 10/05/2026', 'The undersigned waives any lien right for labor and materials furnished through the date of this waiver.'),
    want: { customer_name: 'Mesa Unified Facilities', service_date: '2026-10-05' }, must: [], never: ['cost', 'invoice_number'] },
  { name: 'equipment rental agreement with on-rent / off-rent dates', own: DP, type: 'agreement',
    text: L('EQUIPMENT RENTAL AGREEMENT', 'Customer: Cactus Roofing Inc', 'On-Rent Date: 03/02/2026', 'Off-Rent Date: 03/09/2026', 'Rental Rate: $450.00 per week'),
    want: { customer_name: 'Cactus Roofing Inc', agreement_term: '03/02/2026 to 03/09/2026' }, must: ['customer_name'], never: ['cost'] },
  { name: 'invoice that mentions an off-rent date (not the document date)', own: DP, type: 'invoice',
    text: L('Sunbelt Rentals Mesa', 'INVOICE', 'Invoice #: 90455', 'Invoice Date: 03/10/2026', 'Bill To: Cactus Roofing Inc', 'Off-Rent Date: 03/09/2026', 'Total Due: $612.40'),
    want: { vendor: 'Sunbelt Rentals Mesa', customer_name: 'Cactus Roofing Inc', service_date: '2026-03-10', cost: '612.40', invoice_number: '90455' }, must: ['service_date', 'cost', 'invoice_number'] },
  { name: 'explanation of benefits (claim number, no total owed to a vendor)', own: DP, type: 'statement',
    text: L('EXPLANATION OF BENEFITS', 'THIS IS NOT A BILL', 'Member: Dana Whitfield', 'Claim #: 88321004', 'Date of Service: 08/14/2026', 'Amount Billed: $420.00', 'Plan Paid: $310.00'),
    want: { customer_name: 'Dana Whitfield', service_date: '2026-08-14', invoice_number: '88321004' }, must: ['customer_name', 'service_date'], never: ['cost'] },
  { name: 'EOB with a policyholder line (policyholder is the member, never the vendor)', own: DP, type: 'statement',
    text: L('EXPLANATION OF BENEFITS', 'Policyholder: Dana Whitfield', 'Claim #: 88321004', 'Date of Service: 08/14/2026'),
    want: { service_date: '2026-08-14', invoice_number: '88321004' }, must: ['service_date'], never: ['vendor', 'customer_name', 'cost'] },
  { name: 'superbill (patient, date of service, total charges)', own: ['Desert Dental Group'], type: 'statement',
    text: L('SUPERBILL', 'Patient Name: Dana Whitfield', 'Date of Service: 08/14/2026', 'Procedure: D1110 prophylaxis', 'Total Charges: $240.00'),
    want: { customer_name: 'Dana Whitfield', service_date: '2026-08-14', cost: '240.00' }, must: ['customer_name', 'service_date', 'cost'] },
  { name: 'donor acknowledgment (gift date, gift amount, gift id)', own: ['Hope Harbor Foundation'], type: 'receipt',
    text: L('Hope Harbor Foundation', 'DONOR ACKNOWLEDGMENT', 'Donor Name: Priya Nair', 'Date of Gift: 12/20/2025', 'Gift Amount: $250.00', 'Gift ID: G-5531', 'No goods or services were provided in exchange for this gift.'),
    want: { customer_name: 'Priya Nair', service_date: '2025-12-20', cost: '250.00', invoice_number: 'G-5531' }, must: ['customer_name', 'service_date', 'cost'], never: ['vendor'] },
  { name: 'donation receipt, amount donated', own: ['Hope Harbor Foundation'], type: 'receipt',
    text: L('Hope Harbor Foundation', 'DONATION RECEIPT', 'Receipt No. 332', 'Donor: Ana Pruitt', 'Date of Donation: 01/09/2026', 'Amount Donated: $75.00'),
    want: { customer_name: 'Ana Pruitt', service_date: '2026-01-09', cost: '75.00', invoice_number: '332' }, must: ['customer_name', 'service_date', 'cost'], never: ['vendor'] },
  { name: 'PO with Ship To / Bill To (Bill To is us)', own: ['Juniper Lane Mercantile'], type: 'purchase-order',
    text: L('PURCHASE ORDER', 'PO Number: PO-7782', 'Order Date: 09/01/2026', 'Vendor: Saguaro Paper Supply LLC', 'Ship To: Juniper Lane Mercantile, 55 Palm Rd, Mesa AZ', 'Bill To: Juniper Lane Mercantile, LLC', 'Total: $980.00'),
    want: { vendor: 'Saguaro Paper Supply LLC', service_date: '2026-09-01', cost: '980.00', invoice_number: 'PO-7782' }, must: ['vendor', 'cost'], never: ['customer_name'] },
  { name: 'invoice that quotes the customer PO (PO number is not the invoice number)', own: DP, type: 'invoice',
    text: L('INVOICE', 'Invoice #: 5001', 'Invoice Date: 06/12/2026', 'Bill To: Mesa Unified Facilities', 'PO Number: PO-1234', 'Amount Due: $1,100.00'),
    want: { customer_name: 'Mesa Unified Facilities', service_date: '2026-06-12', cost: '1100.00', invoice_number: '5001' }, must: ['customer_name', 'service_date', 'cost', 'invoice_number'] },
  { name: 'will-call ticket (counter pickup)', own: DP, type: 'delivery-ticket',
    text: L('WILL CALL TICKET', 'Ticket #: WC-221', 'Pickup Date: 06/03/2026', 'Customer: Lena Ortiz', 'Items: 1 condenser fan motor'),
    want: { customer_name: 'Lena Ortiz', service_date: '2026-06-03', invoice_number: 'WC-221' }, must: ['customer_name', 'service_date', 'invoice_number'], never: ['cost'] },
  { name: 'packing list (Ship To, ship date)', own: DP, type: 'delivery-ticket',
    text: L('PACKING LIST', 'Packing Slip #: PL-9910', 'Ship Date: 06/02/2026', 'Ship To: Lena Ortiz', 'Contents: 2 boxes'),
    want: { customer_name: 'Lena Ortiz', service_date: '2026-06-02', invoice_number: 'PL-9910' }, must: [], never: ['cost'] },
  { name: 'bill of lading (consignee, delivery date)', own: DP, type: 'delivery-ticket',
    text: L('BILL OF LADING', 'Reference #: BL-7712', 'Delivery Date: 07/11/2026', 'Consignee: Blue Mesa Analytics Inc', 'Pieces: 4 pallets'),
    want: { customer_name: 'Blue Mesa Analytics Inc', service_date: '2026-07-11', invoice_number: 'BL-7712' }, must: ['service_date'], never: ['cost'] },
  { name: 'offer letter (candidate, offer date)', own: DP, type: 'hr-letter',
    text: L('OFFER LETTER', 'Offer Date: 05/01/2026', 'Candidate Name: Sam Torres', 'Start Date: 06/01/2026', 'We are pleased to offer you the position of service technician.'),
    want: { customer_name: 'Sam Torres', service_date: '2026-05-01' }, must: [], never: ['cost', 'invoice_number'] },
  { name: 'residential lease (tenant, lease start / end)', own: ['Palo Verde Property Management'], type: 'agreement',
    text: L('RESIDENTIAL LEASE AGREEMENT', 'Tenant: Maria Lopez', 'Landlord: Palo Verde Property Management', 'Lease Start Date: 08/01/2026', 'Lease End Date: 07/31/2027', 'Monthly Rent: $1,450.00'),
    want: { customer_name: 'Maria Lopez', agreement_term: '08/01/2026 - 07/31/2027' }, must: ['customer_name'], never: ['vendor'] },
  { name: 'subcontract (between parties, effective date, contract term)', own: DP, type: 'agreement',
    text: L('SUBCONTRACT AGREEMENT', 'Between: Desert Peak Services LLC and Cactus Roofing Inc', 'Effective Date: 02/10/2026', 'Contract Term: 12 months'),
    want: { customer_name: 'Cactus Roofing Inc', service_date: '2026-02-10', agreement_term: '12 months' }, must: ['customer_name'], never: ['cost'] },
  { name: 'grant award letter (grant period, effective date)', own: ['Hope Harbor Foundation'], type: 'agreement',
    text: L('GRANT AWARD LETTER', 'Effective Date: 07/01/2026', 'Grant Period: 07/01/2026 - 06/30/2027', 'Customer: Valley Community Fund'),
    want: { customer_name: 'Valley Community Fund', service_date: '2026-07-01', agreement_term: '07/01/2026 - 06/30/2027' }, must: [], never: ['cost'] },
  { name: 'MOU (parties, effective date, plan term)', own: DP, type: 'agreement',
    text: L('MEMORANDUM OF UNDERSTANDING', 'Parties: Desert Peak Services LLC and Blue Mesa Analytics Inc.', 'Effective Date: 04/15/2026', 'Plan Term: 18 months'),
    want: { customer_name: 'Blue Mesa Analytics Inc.', service_date: '2026-04-15', agreement_term: '18 months' }, must: ['customer_name'], never: ['cost'] },
  { name: 'rent roll (statement date only; no customer)', own: ['Palo Verde Property Management'], type: 'statement',
    text: L('Palo Verde Property Management', 'RENT ROLL', 'Statement Date: 09/30/2026', 'Unit 14B   Maria Lopez   $1,450.00', 'Unit 15A   Tom Reed   $1,525.00'),
    want: { service_date: '2026-09-30' }, must: ['service_date'], never: ['customer_name', 'cost'] },
  { name: 'tenant ledger (balance forward, balance due)', own: ['Palo Verde Property Management'], type: 'statement',
    text: L('Palo Verde Property Management', 'TENANT LEDGER', 'Tenant: Maria Lopez', 'Unit: 14B', 'Statement Date: 10/31/2026', 'Balance Forward: $0.00', 'Balance Due: $1,450.00'),
    want: { customer_name: 'Maria Lopez', service_date: '2026-10-31', cost: '1450.00' }, must: ['customer_name', 'service_date'] },
  { name: 'owner statement (period ending)', own: ['Palo Verde Property Management'], type: 'statement',
    text: L('Palo Verde Property Management', 'OWNER STATEMENT', 'Period Ending: 09/30/2026', 'Net Due: $3,120.55'),
    want: { service_date: '2026-09-30', cost: '3120.55' }, must: ['service_date'] },
  { name: 'contractor invoice with make checks payable to', own: ['Juniper Lane Mercantile'], type: 'invoice',
    text: L('INVOICE', 'Invoice No: 3318', 'Invoice Date: 08/08/2026', 'Billing Name: Juniper Lane Mercantile', 'Make Checks Payable To: Cactus Roofing Inc', 'Amount Payable: $2,300.00'),
    want: { vendor: 'Cactus Roofing Inc', service_date: '2026-08-08', cost: '2300.00', invoice_number: '3318' }, must: ['service_date', 'cost', 'invoice_number'], never: ['customer_name'] },
  { name: 'clinic receipt (encounter date, amount paid)', own: ['Desert Dental Group'], type: 'receipt',
    text: L('Desert Dental Group', 'RECEIPT', 'Receipt #: 1190', 'Patient: Ron Diaz', 'Encounter Date: 05/05/2026', 'Amount Paid: $30.00'),
    want: { customer_name: 'Ron Diaz', service_date: '2026-05-05', cost: '30.00', invoice_number: '1190' }, must: ['customer_name', 'service_date', 'cost'], never: ['vendor'] },
  { name: 'law-firm bill (professional fees, balance due)', own: ['Cactus Roofing Inc'], type: 'invoice',
    text: L('Hale & Brandt LLP', 'Attorneys at Law', 'INVOICE', 'Invoice #: 5588', 'Invoice Date: 09/30/2026', 'Client: Cactus Roofing Inc', 'Professional Fees: $1,800.00', 'Balance Due: $1,800.00'),
    want: { vendor: 'Hale & Brandt LLP', service_date: '2026-09-30', cost: '1800.00', invoice_number: '5588' }, must: ['service_date', 'cost', 'invoice_number'], never: ['customer_name'] },
  { name: 'account statement with previous balance', own: DP, type: 'statement',
    text: L('ACCOUNT STATEMENT', 'Statement #: ST-4410', 'Statement Date: 09/30/2026', 'Customer: Mesa Unified Facilities', 'Previous Balance: $500.00', 'Total Due: $1,740.00'),
    want: { customer_name: 'Mesa Unified Facilities', service_date: '2026-09-30', cost: '1740.00', invoice_number: 'ST-4410' }, must: ['customer_name', 'service_date', 'cost'] },
  { name: 'service invoice with date svc shorthand', own: DP, type: 'invoice',
    text: L('INVOICE', 'Inv #: 8821', 'Date Svc: 07/21/2026', 'Bill To: Lena Ortiz', 'Total Due: $310.00'),
    want: { customer_name: 'Lena Ortiz', service_date: '2026-07-21', cost: '310.00', invoice_number: '8821' }, must: ['customer_name', 'cost'] },
  { name: 'insurance certificate: exp date and valid through do not become the document date', own: DP, type: 'insurance-certificate',
    text: L('CERTIFICATE OF INSURANCE', 'Named Insured: Cactus Roofing Inc', 'Policy Number: AU-77120', 'Valid Through: 11/30/2026'),
    want: { vendor: 'Cactus Roofing Inc' }, must: ['vendor'], never: ['customer_name', 'cost', 'service_date'] },
  { name: 'PROSE: payable-to / amount due / policy period inside sentences', own: DP, type: 'invoice',
    text: L('Account notice', 'Please make checks payable to Acme Supply within 30 days of receipt. The amount due is discussed on page two, and the policy period renewal is separate.', 'Your invoice number is printed under the barcode, and the balance due after credits will be billed next month.'),
    want: {}, must: [], never: ['customer_name', 'vendor', 'service_date', 'cost', 'invoice_number', 'agreement_term'] },
  { name: 'PROSE: lease start / on-rent / received from inside sentences', own: DP, type: 'agreement',
    text: L('Notes to the file', 'The lease start date will be confirmed once the unit is ready, and the on-rent date depends on delivery of the lift.', 'Payment received from the tenant is posted by the office; the contract term is twelve months.'),
    want: {}, must: [], never: ['customer_name', 'vendor', 'service_date', 'cost', 'invoice_number', 'agreement_term'] },
  { name: 'PROSE: date of service / amount paid / bill to inside sentences', own: DP, type: 'receipt',
    text: L('Thank you for your business.', 'The date of service was last week and the amount paid was reported to you earlier; send any bill to our office with the claim # from the letter.'),
    want: {}, must: [], never: ['customer_name', 'vendor', 'service_date', 'cost', 'invoice_number', 'agreement_term'] },
];
