# R39: regenerates api/_lib/router/lexicon.generated.js from the system Hunspell en_US dictionary (/usr/share/hunspell). Usage: python3 scripts/gen-lexicon.py
import re,sys
aff=open('/usr/share/hunspell/en_US.aff',encoding='utf-8').read().split('\n')
rules={}  # flag -> (type, cross, [(strip, add, cond)])
i=0
cur=None
for line in aff:
    p=line.split()
    if len(p)>=4 and p[0] in('PFX','SFX') and p[3].isdigit():
        cur=(p[0],p[2]=='Y'); rules[p[1]]=[cur[0],cur[1],[]]
    elif len(p)>=5 and p[0] in('PFX','SFX') and p[1] in rules:
        strip=p[2] if p[2]!='0' else ''
        add=p[3].split('/')[0]; add='' if add=='0' else add
        cond=p[4]
        rules[p[1]][2].append((strip,add,cond))
def cond_re(c,typ):
    if c=='.': return None
    return re.compile((c+'$') if typ=='SFX' else ('^'+c))
comp={}
def forms(word,flags):
    out={word}
    sfx=[];pfx=[]
    for f in flags:
        r=rules.get(f)
        if not r: continue
        typ,cross,lst=r
        for strip,add,cond in lst:
            cr=comp.setdefault((f,cond,typ),cond_re(cond,typ))
            if cr is not None and not cr.search(word): continue
            if typ=='SFX':
                if strip and not word.endswith(strip): continue
                w=word[:len(word)-len(strip)]+add if strip else word+add
                out.add(w); 
                if cross: sfx.append(w)
            else:
                if strip and not word.startswith(strip): continue
                w=add+word[len(strip):]
                out.add(w)
                if cross: pfx.append(w)
    return out
lower=set(); proper=set()
for line in open('/usr/share/hunspell/en_US.dic',encoding='utf-8').read().split('\n')[1:]:
    if not line.strip(): continue
    w,_,fl=line.partition('/')
    fl=fl.strip()
    if not re.fullmatch(r"[A-Za-z]+",w): continue
    fs=forms(w,fl)
    if w[0].islower(): lower|= {x for x in fs if re.fullmatch(r'[a-z]+',x)}
    else: proper|={x.lower() for x in fs if re.fullmatch(r'[A-Za-z]+',x)}
common=lower
words=sorted(w for w in common if 2<=len(w)<=12)
import os
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
hdr = """/**
 * GENERATED by scripts/gen-lexicon.py (R39). Ordinary English word forms: the lowercase entries of the Hunspell en_US dictionary with affixes
 * expanded (2-12 letters). A word that exists in that dictionary ONLY capitalized (Dana, Whitfield, Tucson, Wayne) is not in this list, so it reads as
 * a name. Used ONLY by router/leftover.js to tell a plain word from a name; it holds no brand, city or person list. Source: Hunspell en_US
 * (SCOWL-derived, permissive license). Do not edit by hand.
 */
export const COMMON_WORDS = `"""
open(os.path.join(root,'api','_lib','router','lexicon.generated.js'),'w').write(hdr+' '.join(words)+'`;\n')
print(len(words),'words written',file=sys.stderr)
