-- ============================================================================
-- 07-multi-user.sql — run AFTER 06-warranty-indexes.sql. Idempotent; safe to
-- re-run, same style as 02/05.
--
-- Enables real multi-user shops: several Clerk users sharing one tenant.
--
-- PART 1 fixes a constraint that made this impossible. 01-create-schema.sql
-- gave `users.clerk_user_id` a GLOBAL `UNIQUE`, on top of the intended
-- `UNIQUE(tenant_id, clerk_user_id)`. A Clerk identity is globally unique, but
-- a PERSON is not confined to one tenant: a technician who contracts for two
-- HVAC shops belongs to two tenants, each with its own `users` row for the
-- same clerk_user_id. The global constraint made the second row impossible to
-- insert — api/_lib/members.js's upsertMember() would fail with a unique
-- violation on the SECOND shop, not the first, which is exactly the kind of
-- bug that hides until day two of a pilot.
--
-- PART 2 is `merge_tenant()`, for the mirror-image case: a technician uploads
-- documents BEFORE joining a shop (their own solo `user_<clerkUserId>`
-- tenant — see api/_lib/auth.js's fallback), then creates or joins a shop.
-- Their solo-tenant data does not follow them automatically — nothing moves
-- tenant_id on its own — so this gives an explicit, auditable way to fold one
-- solo tenant's rows into a shop tenant. src/screens/OnboardingScreen.tsx
-- calls it (indirectly, through an endpoint the API-owning engineers still
-- need to add — see HANDOFF.md) whenever a signed-in user with previously
-- solo data joins or creates a shop.
-- ============================================================================


-- ============================================================================
-- PART 1 — one person, many shops
-- ============================================================================

-- ---- 1a. drop the GLOBAL unique constraint on clerk_user_id -----------------
--
-- Finds it by its actual column, not by the name Postgres happened to
-- generate for an inline `UNIQUE` (`users_clerk_user_id_key`, undocumented and
-- not something this file should assume survived every environment's setup
-- unchanged). Matches only a SINGLE-column unique constraint on
-- clerk_user_id — the composite UNIQUE(tenant_id, clerk_user_id) constraint
-- this migration KEEPS has two columns and is untouched by this loop.
DO $$
DECLARE
  v_attnum int;
  r record;
BEGIN
  SELECT attnum INTO v_attnum
    FROM pg_attribute
   WHERE attrelid = 'users'::regclass AND attname = 'clerk_user_id' AND NOT attisdropped;

  IF v_attnum IS NULL THEN
    RAISE EXCEPTION '07-multi-user.sql: users.clerk_user_id column not found';
  END IF;

  FOR r IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'users'::regclass
       AND contype = 'u'
       AND conkey::int[] = ARRAY[v_attnum]  -- exactly one column, and it's this one
  LOOP
    EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', r.conname);
  END LOOP;
END $$;

-- ---- 1b. make sure UNIQUE(tenant_id, clerk_user_id) exists ------------------
--
-- Already created inline by 01-create-schema.sql in every environment that
-- ran it — this is a safety net, not the primary mechanism, for any database
-- that reaches this file without 01's exact table definition (e.g. a
-- hand-repaired one). Matched by COLUMN SET, not by name, for the same reason
-- as 1a: an inline table-level UNIQUE's autogenerated name is not a contract.
DO $$
DECLARE
  v_tenant_attnum int;
  v_clerk_attnum  int;
  v_exists boolean;
BEGIN
  SELECT attnum INTO v_tenant_attnum FROM pg_attribute
   WHERE attrelid = 'users'::regclass AND attname = 'tenant_id' AND NOT attisdropped;
  SELECT attnum INTO v_clerk_attnum FROM pg_attribute
   WHERE attrelid = 'users'::regclass AND attname = 'clerk_user_id' AND NOT attisdropped;

  SELECT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'users'::regclass
       AND contype = 'u'
       AND conkey::int[] = ARRAY[v_tenant_attnum, v_clerk_attnum]
  ) INTO v_exists;

  IF NOT v_exists THEN
    ALTER TABLE users ADD CONSTRAINT users_tenant_id_clerk_user_id_key UNIQUE (tenant_id, clerk_user_id);
  END IF;
END $$;


-- ============================================================================
-- PART 2 — merge_tenant(): fold a solo tenant into a shop
-- ============================================================================
--
-- SECURITY DEFINER, and the one function in this codebase that is DELIBERATELY
-- cross-tenant — every other query in the system (resolve_tenant included)
-- only ever touches the ONE tenant named by app.tenant_id. This one exists
-- precisely to move rows from tenant A to tenant B in a single call, which is
-- the one operation RLS is specifically designed to make impossible for an
-- ordinary connection. That makes its own argument-level safety the WHOLE
-- boundary, not a backstop next to RLS:
--
--   1. `from_key` MUST match `^user_` — the shape api/_lib/auth.js gives a
--      solo tenant (`user_<clerkUserId>`), never a Clerk org id (`org_...`).
--      This is the load-bearing check: it makes it structurally impossible to
--      call this function to move one REAL SHOP's data into another, because
--      a shop's tenant key can never match `^user_`. The worst this function
--      can ever do, argument-wise, is drain a one-person tenant — which by
--      construction holds only that one person's own data.
--   2. `to_key` must already exist as a tenant (this function does not create
--      one — resolve_tenant() is how a tenant is created, via an authenticated
--      request, which is a stronger guarantee than anything a bare string
--      argument here could offer).
--   3. `from_key <> to_key` — merging a tenant into itself is refused outright
--      rather than silently accepted as a no-op, so a caller passing the same
--      value twice by mistake finds out immediately.
--
-- What this function CANNOT check: WHO is asking. A bare `(text, text)`
-- function has no notion of "the caller's own solo tenant" — only the code
-- that calls it does. THE CALLING API ROUTE MUST VERIFY, from the caller's
-- OWN verified auth (never from client-supplied ids):
--   - from_key = 'user_' || that caller's OWN Clerk userId (never someone
--     else's solo tenant), and
--   - to_key   = that caller's CURRENT active-org tenant key.
-- EXECUTE is granted only to the tenant-scoped application roles below, never
-- to PUBLIC, but that only keeps a raw SQL client out — it does not replace
-- the caller-identity check above, which belongs in the HTTP route. See
-- HANDOFF.md: that route does not exist yet and is not this file's to add.
--
-- IDEMPOTENT: safe to call twice for the same pair. A from_key with no tenant
-- row yet (this person never actually uploaded anything solo) is a no-op, not
-- an error — the caller's real goal ("this technician's data, if any, ends up
-- in the shop") is already true.
CREATE OR REPLACE FUNCTION merge_tenant(from_key text, to_key text)
RETURNS TABLE(moved_table text, moved_rows bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_from       uuid;
  v_to         uuid;
  v_rows       bigint;
  v_rows2      bigint;
  v_max_ver    int;
  r            record;
  v_new_user   uuid;
BEGIN
  IF from_key IS NULL OR to_key IS NULL
     OR length(trim(from_key)) = 0 OR length(trim(to_key)) = 0 THEN
    RAISE EXCEPTION 'merge_tenant: from_key and to_key are required';
  END IF;

  IF from_key = to_key THEN
    RAISE EXCEPTION 'merge_tenant: from_key and to_key must differ';
  END IF;

  -- The load-bearing safety check — see the header. Never relaxed.
  IF from_key !~ '^user_' THEN
    RAISE EXCEPTION 'merge_tenant: from_key must be a solo tenant key (user_<clerkUserId>), got %', from_key;
  END IF;

  SELECT id INTO v_to FROM tenants WHERE clerk_org_id = to_key;
  IF v_to IS NULL THEN
    RAISE EXCEPTION 'merge_tenant: destination tenant % does not exist yet', to_key;
  END IF;

  SELECT id INTO v_from FROM tenants WHERE clerk_org_id = from_key;
  IF v_from IS NULL THEN
    RETURN; -- nothing was ever uploaded solo — idempotent no-op, see header.
  END IF;

  IF v_from = v_to THEN
    RETURN; -- already merged in an earlier call — idempotent no-op.
  END IF;

  -- ---- documents: dedupe by sha256_hash before moving ----------------------
  -- documents has UNIQUE(tenant_id, sha256_hash). If the same file was
  -- uploaded independently to both tenants (a technician scans an invoice
  -- solo, and the shop's office already has the same invoice on file), a
  -- blind UPDATE of tenant_id would collide on that constraint. Rather than
  -- create a duplicate document that then fights the constraint, repoint the
  -- solo copy's facets/extractions at the shop's EXISTING document (same
  -- bytes, by definition of matching sha256_hash) and drop the solo
  -- duplicate. document_pages is NOT repointed the same way: it carries its
  -- own UNIQUE(document_id, page_no), and the destination document — same
  -- file — already has its own page rows, so the solo copy's pages are
  -- simply dropped rather than collide.
  FOR r IN
    SELECT d.id AS old_id, existing.id AS dest_id
      FROM documents d
      JOIN documents existing
        ON existing.tenant_id = v_to AND existing.sha256_hash = d.sha256_hash
     WHERE d.tenant_id = v_from
  LOOP
    DELETE FROM document_pages WHERE document_id = r.old_id;
    UPDATE facets      SET document_id = r.dest_id WHERE document_id = r.old_id;
    UPDATE extractions SET document_id = r.dest_id WHERE document_id = r.old_id;
    DELETE FROM documents WHERE id = r.old_id;
  END LOOP;

  -- Every document remaining under v_from now has a hash the destination does
  -- not have, so this cannot collide with UNIQUE(tenant_id, sha256_hash).
  UPDATE documents SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'documents'; moved_rows := v_rows; RETURN NEXT;

  -- ---- document_pages, facets, extractions ---------------------------------
  -- Their own tenant_id column (document_pages has carried one since
  -- 03-retrieval.sql — RLS on it does not go through documents). Whatever
  -- still has tenant_id = v_from at this point either belongs to a document
  -- just moved above, or — for the repointed rows from the loop — already
  -- points at a v_to document but hasn't had ITS OWN tenant_id column moved
  -- yet, which this statement does now.
  UPDATE document_pages SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'document_pages'; moved_rows := v_rows; RETURN NEXT;

  UPDATE facets SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'facets'; moved_rows := v_rows; RETURN NEXT;

  UPDATE extractions SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'extractions'; moved_rows := v_rows; RETURN NEXT;

  -- Review links (08-review.sql). Guarded because 07 may run before 08 on a
  -- fresh database; on a database where the table exists, skipping this would
  -- let the final DELETE FROM tenants cascade-delete every link the solo user
  -- made — who linked what to which unit, silently gone on the day they join
  -- their shop.
  IF EXISTS (SELECT 1 FROM information_schema.tables
              WHERE table_schema = 'public' AND table_name = 'document_entity_links') THEN
    EXECUTE 'UPDATE document_entity_links SET tenant_id = $1 WHERE tenant_id = $2'
      USING v_to, v_from;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    moved_table := 'document_entity_links'; moved_rows := v_rows; RETURN NEXT;
  END IF;

  -- ---- entities: customers before equipment --------------------------------
  -- entities has a trigger (enforce_customer_link, 05-customer-link.sql) that
  -- fires on UPDATE OF tenant_id and rejects an equipment row whose
  -- customer_id points at a DIFFERENT tenant than the row's own new
  -- tenant_id. A single UPDATE touching every entity at once would trip that
  -- for any equipment row already linked to a customer — moving both rows in
  -- the same statement does not guarantee the customer's new tenant_id is
  -- visible yet when the trigger checks the equipment row moving alongside
  -- it. Two statements, customers (and every other non-equipment type) first,
  -- sidesteps this entirely: by the time equipment rows move, every
  -- customer_id they can legally point at (same solo tenant, per that same
  -- trigger enforcing it at write time) is already sitting at v_to.
  UPDATE entities SET tenant_id = v_to WHERE tenant_id = v_from AND entity_type <> 'equipment';
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  UPDATE entities SET tenant_id = v_to WHERE tenant_id = v_from AND entity_type = 'equipment';
  GET DIAGNOSTICS v_rows2 = ROW_COUNT;
  moved_table := 'entities'; moved_rows := v_rows + v_rows2; RETURN NEXT;

  -- ---- proposals, schema_versions, audit_log, users ------------------------
  --
  -- users moves FIRST and is remapped id-for-id, not blindly UPDATEd: a solo
  -- tenant's user row may already have a counterpart in the shop (this same
  -- technician, already a member via api/_lib/members.js's upsertMember, which
  -- runs on every request against their now-active org — very likely to have
  -- already run before this function is ever called). audit_log.user_id,
  -- schema_versions.created_by and proposals.resolved_by all reference
  -- users(id) ON DELETE SET NULL; without this remap, deleting the old user
  -- row at the end would silently null out exactly the attribution this
  -- feature exists to add.
  FOR r IN SELECT id, clerk_user_id, email, role, created_at FROM users WHERE tenant_id = v_from LOOP
    SELECT id INTO v_new_user FROM users WHERE tenant_id = v_to AND clerk_user_id = r.clerk_user_id;
    IF v_new_user IS NULL THEN
      INSERT INTO users (tenant_id, clerk_user_id, email, role, created_at)
      VALUES (v_to, r.clerk_user_id, r.email, r.role, r.created_at)
      RETURNING id INTO v_new_user;
    END IF;
    UPDATE audit_log       SET user_id     = v_new_user WHERE tenant_id = v_from AND user_id     = r.id;
    UPDATE schema_versions SET created_by  = v_new_user WHERE tenant_id = v_from AND created_by  = r.id;
    UPDATE proposals       SET resolved_by = v_new_user WHERE tenant_id = v_from AND resolved_by = r.id;
  END LOOP;
  DELETE FROM users WHERE tenant_id = v_from;

  UPDATE proposals SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'proposals'; moved_rows := v_rows; RETURN NEXT;

  -- schema_versions has UNIQUE(tenant_id, version) — a fresh version counter
  -- per tenant, so both tenants likely already have a version 1. Renumber the
  -- incoming rows to continue after the destination's current max, preserving
  -- their relative order without colliding. (extractions.schema_version is an
  -- unused column today — recordsStore.js's createExtraction never sets it —
  -- so nothing downstream depends on the OLD numbers surviving unchanged.)
  SELECT COALESCE(MAX(version), 0) INTO v_max_ver FROM schema_versions WHERE tenant_id = v_to;
  UPDATE schema_versions
     SET tenant_id = v_to, version = version + v_max_ver
   WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'schema_versions'; moved_rows := v_rows; RETURN NEXT;

  UPDATE audit_log SET tenant_id = v_to WHERE tenant_id = v_from;
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  moved_table := 'audit_log'; moved_rows := v_rows; RETURN NEXT;

  -- ---- drop the now-empty solo tenant --------------------------------------
  -- Every table above has already been moved off v_from, so this cascade
  -- (documents/facets/extractions/entities/proposals/schema_versions/
  -- audit_log/users all REFERENCE tenants(id) ON DELETE CASCADE) deletes
  -- nothing but the empty tenant row itself.
  DELETE FROM tenants WHERE id = v_from;

  RETURN;
END;
$$;

-- KNOWN LIMITATION, accepted rather than guessed around (same philosophy as
-- findOrCreateCustomer / findOrCreateEquipment in recordsStore.js): if the
-- solo tenant and the shop each independently created an equipment or
-- customer entity for the same real unit or person, this produces TWO rows
-- in the shop after the merge rather than one. Nothing in this migration
-- guesses which pairs are "the same" — a wrong guess here means treating two
-- different customers' equipment as one and mixing their warranty history,
-- which recordsStore.js's own comments call a privacy defect, not an untidy
-- table. A visible duplicate a human can merge later is the safer failure.

DO $$
DECLARE r_role text;
BEGIN
  FOREACH r_role IN ARRAY ARRAY['deepwell_rls', 'deepwell_app'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r_role) THEN
      EXECUTE format('GRANT EXECUTE ON FUNCTION merge_tenant(text, text) TO %I', r_role);
    END IF;
  END LOOP;
END $$;

-- ============================================================================
-- Proof — expected results for a human running this against a real database,
-- same convention as 02/03/05. Nothing here executes automatically.
-- ============================================================================

-- Expect: 0 rows. Any row here is a single-column unique constraint left on
-- clerk_user_id — the bug this migration exists to fix.
SELECT con.conname
  FROM pg_constraint con
  JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attname = 'clerk_user_id'
 WHERE con.conrelid = 'users'::regclass AND con.contype = 'u' AND con.conkey::int[] = ARRAY[att.attnum::int];

-- Expect: exactly one row — the composite constraint this migration keeps.
SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
 WHERE conrelid = 'users'::regclass AND contype = 'u';

-- Expect: one row, prosecdef = true (SECURITY DEFINER).
SELECT proname, prosecdef FROM pg_proc WHERE proname = 'merge_tenant';

-- Expect: EXECUTE granted to deepwell_rls/deepwell_app (whichever exist) and
-- to no one else — this function must never be reachable from an arbitrary
-- role, only from the application's own tenant-scoped connection.
SELECT grantee, privilege_type FROM information_schema.routine_privileges
 WHERE routine_name = 'merge_tenant';
